import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Scum Audio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
              <ConvexClientProvider>
                {children}
                <Toaster />
              </ConvexClientProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
